### PR TITLE
Upgrade to latest actix

### PR DESCRIPTION
**Pull request by Igosuki**
Hello Norberto, I tried to update to actix's latest release, hope I did it correctly.

### CODE REVIEW

**Comment by Igosuki** [comment]
n.b. : use pin project instead of making B unpin since that conflicts with the other middlewares.

**Comment by nlopes** [comment]
Will take a look at this this week hopefully. Apologies for the late reply

**Comment by Igosuki** [comment]
Asbolutely no worries, we've all got lives ;)

**Comment by nlopes** [comment]
Do you mind taking a look at https://github.com/nlopes/actix-web-prom/pull/25 ? Will merge with your thumbs up @Igosuki .

I kept all your commits. Do you happen to know of a middleware this messes with?
As a side note, I bumped to the latest alphas of actix-web and actix-http.

**Pull request closed without merging**
