### PR TITLE
Added support for masking unmatched paths

### LINKED ISSUE #80: Should not extend metrics response on 404 (Uncontrolled Resource Consumption Vulnerability)
Currently, when an endpoint receives a 404, it extends the Prometheus metrics response by approx ~15 new lines / ~1.5KB.

For example, my server does not include a `/time.php` endpont, so when I was bot scraped by a bot, of these lines were appended.

```sh
# ...
public_api_http_requests_duration_seconds_bucket{endpoint="/time.php",method="GET",status="404",le="0.005"} 1
public_api_http_requests_duration_seconds_bucket{endpoint="/time.php",method="GET",status="404",le="0.01"} 1
public_api_http_requests_duration_seconds_bucket{endpoint="/time.php",method="GET",status="404",le="0.025"} 1
public_api_http_requests_duration_seconds_bucket{endpoint="/time.php",method="GET",status="404",le="0.05"} 1
public_api_http_requests_duration_seconds_bucket{endpoint="/time.php",method="GET",status="404",le="0.1"} 1
public_api_http_requests_duration_seconds_bucket{endpoint="/time.php",method="GET",status="404",le="0.25"} 1
public_api_http_requests_duration_seconds_bucket{endpoint="/time.php",method="GET",status="404",le="0.5"} 1
public_api_http_requests_duration_seconds_bucket{endpoint="/time.php",method="GET",status="404",le="1"} 1
public_api_http_requests_duration_seconds_bucket{endpoint="/time.php",method="GET",status="404",le="2.5"} 1
public_api_http_requests_duration_seconds_bucket{endpoint="/time.php",method="GET",status="404",le="5"} 1
public_api_http_requests_duration_seconds_bucket{endpoint="/time.php",method="GET",status="404",le="10"} 1
public_api_http_requests_duration_seconds_bucket{endpoint="/time.php",method="GET",status="404",le="+Inf"} 1
public_api_http_requests_duration_seconds_sum{endpoint="/time.php",method="GET",status="404"} 0.000011828
public_api_http_requests_duration_seconds_count{endpoint="/time.php",method="GET",status="404"} 1
# ...
public_api_http_requests_total{endpoint="/time.php",method="GET",status="404"} 1
```

Then, repeat for 100+ other 404'ing endpoints, and you end up with a really large metrics response, [resulting in hundreds of GB of egress on your `/metrics` endpoint](https://community.fly.io/t/suprisingly-high-outbound-bandwidth-charges-since-8-jan/17799) (which has been kindly refunded by the Fly.io billing team).

Screenshot from 2024-01-26 15-03-36

Furthermore, a dedicated attacker could certainly exhaust significantly more resources simply by 404ing on more URLs

To resolve this issue, 404 responses from endpoints that fail to match should not be included in metrics. I believe [this PR](https://github.com/nlopes/actix-web-prom/pull/79) should resolve the issue? 

Also recommend submitting an advisory to RustSec for this version of the package.

### PR DESCRIPTION
**Pull request by ranger-ross**
Added support for replacing unmatched path patterns with a user defined `String`.

Should resolve https://github.com/nlopes/actix-web-prom/issues/80

### CODE REVIEW

**Comment by ranger-ross** [comment]
Hey @nlopes 

Just a friendly reminder about this PR. Would love to see it get merged ❤️

**Comment by nlopes** [comment]
Thank you @ranger-ross

**Comment by nlopes** [comment]
I missed this in this PR so ended up pushing a hotfix. If you're working off of latest in `main` please pull again.

https://github.com/nlopes/actix-web-prom/pull/86/files#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R830

**Comment by ranger-ross** [comment]
Ahh, thanks @nlopes 

Any plan to publish a 0.9.0 in the near future?

**Comment by ranger-ross** [comment]
Hey there @nlopes 

Would love to see a new version published with this feature 🙏🏼

**Comment by nlopes** [comment]
Shipped, thanks for the reminder.

**Pull request merged**
